"""production_initial

Revision ID: 74c043449ceb
Revises: 0001_add_data_source_to_sos_signal
Create Date: 2026-06-01 13:08:22.463519
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '74c043449ceb'
down_revision = '0001_add_data_source_to_sos_signal'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rescue_teams_id'), table_name='rescue_teams')
    op.drop_index(op.f('ix_rescue_teams_team_code'), table_name='rescue_teams')
    op.drop_table('rescue_teams')
    op.drop_index(op.f('ix_sos_signals_id'), table_name='sos_signals')
    op.drop_table('sos_signals')
    op.drop_index(op.f('ix_demo_scenarios_id'), table_name='demo_scenarios')
    op.drop_table('demo_scenarios')
    op.drop_index(op.f('ix_cellular_anomalies_id'), table_name='cellular_anomalies')
    op.drop_table('cellular_anomalies')
    op.drop_index(op.f('ix_satellite_zones_id'), table_name='satellite_zones')
    op.drop_table('satellite_zones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_zones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('zone_name', sa.VARCHAR(), nullable=False),
    sa.Column('center_lat', sa.FLOAT(), nullable=False),
    sa.Column('center_lng', sa.FLOAT(), nullable=False),
    sa.Column('flood_severity', sa.FLOAT(), nullable=True),
    sa.Column('area_sqkm', sa.FLOAT(), nullable=True),
    sa.Column('isolated_structures', sa.INTEGER(), nullable=True),
    sa.Column('water_depth_estimate', sa.FLOAT(), nullable=True),
    sa.Column('scenario_id', sa.VARCHAR(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_zones_id'), 'satellite_zones', ['id'], unique=False)
    op.create_table('cellular_anomalies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tower_id', sa.VARCHAR(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lng', sa.FLOAT(), nullable=False),
    sa.Column('anomaly_type', sa.VARCHAR(), nullable=True),
    sa.Column('anomaly_score', sa.FLOAT(), nullable=True),
    sa.Column('affected_radius_km', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cellular_anomalies_id'), 'cellular_anomalies', ['id'], unique=False)
    op.create_table('demo_scenarios',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('scenario_name', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('disaster_type', sa.VARCHAR(), nullable=True),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('total_affected', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_scenarios_id'), 'demo_scenarios', ['id'], unique=False)
    op.create_table('sos_signals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('raw_message', sa.TEXT(), nullable=False),
    sa.Column('language_detected', sa.VARCHAR(), nullable=True),
    sa.Column('language_confidence', sa.FLOAT(), nullable=True),
    sa.Column('has_survivor_signal', sa.BOOLEAN(), nullable=True),
    sa.Column('survivor_count_estimate', sa.INTEGER(), nullable=True),
    sa.Column('location_extracted', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('priority_score', sa.FLOAT(), nullable=True),
    sa.Column('priority_level', sa.VARCHAR(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('data_source', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_signals_id'), 'sos_signals', ['id'], unique=False)
    op.create_table('rescue_teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team_name', sa.VARCHAR(), nullable=False),
    sa.Column('team_code', sa.VARCHAR(), nullable=False),
    sa.Column('unit_type', sa.VARCHAR(), nullable=True),
    sa.Column('current_lat', sa.FLOAT(), nullable=False),
    sa.Column('current_lng', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('assigned_signal_id', sa.INTEGER(), nullable=True),
    sa.Column('personnel_count', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_signal_id'], ['sos_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rescue_teams_team_code'), 'rescue_teams', ['team_code'], unique=1)
    op.create_index(op.f('ix_rescue_teams_id'), 'rescue_teams', ['id'], unique=False)
    # ### end Alembic commands ###
